interface InvestigationReportPanelProps {
  report: string;
}

/** Displays Gemini's report exactly as returned by the backend, typeset as a formal document. */
export function InvestigationReportPanel({ report }: InvestigationReportPanelProps) {
  const paragraphs = report
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .filter(Boolean);

  return (
    <div className="paper-card px-6 py-8 sm:px-10">
      <div className="flex flex-wrap items-center justify-between gap-x-8 gap-y-3 border-b border-line pb-5">
        <div>
          <p className="label-meta">Generated By</p>
          <p className="mt-0.5 font-mono text-xs text-ink">D.F.I. Analysis System</p>
        </div>
        <div>
          <p className="label-meta">Report Status</p>
          <p className="mt-0.5 font-mono text-xs text-investigation">Final</p>
        </div>
      </div>

      <h2 className="mt-6 font-serif text-lg uppercase tracking-wide text-ink">
        Investigation Report
      </h2>

      <div className="mt-4 animate-reveal space-y-4 font-serif text-[15px] leading-relaxed text-ink/90">
        {paragraphs.length > 0 ? (
          paragraphs.map((paragraph, i) => <p key={i}>{paragraph}</p>)
        ) : (
          <p className="italic text-muted">No report text was returned for this case.</p>
        )}
      </div>
    </div>
  );
}
